// Code generated by protoc-gen-hcplugin. DO NOT EDIT.
package netrpc

import (
	base "github.com/da-moon/protoc-gen-hcplugin/example/proto"

	rpc "net/rpc"

	stacktrace "github.com/palantir/stacktrace"
)

// Client is an implementation of shared that talks over RPC.
type Client struct{ client *rpc.Client }

func (c *Client) Get(key string) ([]byte, error) {
	var _resp base.GetResponse
	err := c.client.Call("Plugin.Get", &base.GetRequest{
		Key: key,
	}, &_resp)
	if err != nil {
		err = stacktrace.Propagate(err, "Get call failed with request %#v", &base.GetRequest{
			Key: key,
		})
	}
	return _resp.Value, err
}

func (c *Client) Put(key string, value []byte) error {
	var _resp interface{}
	err := c.client.Call("Plugin.Put", &base.PutRequest{
		Key:   key,
		Value: value,
	}, &_resp)
	if err != nil {
		err = stacktrace.Propagate(err, "Put call failed with request %#v", &base.PutRequest{
			Key:   key,
			Value: value,
		})
	}
	return err
}
