// Code generated by protoc-gen-hcplugin. DO NOT EDIT.
package netrpc

import (
	base "github.com/da-moon/protoc-gen-hcplugin/example/proto"

	shared "github.com/da-moon/protoc-gen-hcplugin/example/proto/kv/shared"

	stacktrace "github.com/palantir/stacktrace"
)

// Server - This is the RPC server that Client talks to, conforming to the requirements of net/rpc
type Server struct {
	Impl shared.KVInterface
}

func (s *Server) Get(_req *base.GetRequest, _resp *base.GetResponse) error {
	value, err := s.Impl.Get(
		_req.Key,
	)
	if err != nil {
		err = stacktrace.Propagate(err, "Getrequest call failed with request %#v", &base.GetRequest{
			Key: _req.Key,
		})
		return err
	}

	_resp.Value = value

	return nil

}

func (s *Server) Put(_req *base.PutRequest, _resp *base.Empty) error {
	err := s.Impl.Put(
		_req.Key,
		_req.Value,
	)
	if err != nil {
		err = stacktrace.Propagate(err, "Putrequest call failed with request %#v", &base.PutRequest{
			Key:   _req.Key,
			Value: _req.Value,
		})
		return err
	}

	return nil

}
