// Code generated by protoc-gen-hcplugin. DO NOT EDIT.
package grpc

import (
	base "github.com/da-moon/protoc-gen-hcplugin/example/proto"

	context "context"

	grpcx "google.golang.org/grpc"

	plugin "github.com/hashicorp/go-plugin"

	shared "github.com/da-moon/protoc-gen-hcplugin/example/proto/kv/shared"
)

// GRPCClient is an implementation of shared that talks over gRPC.
type Plugin struct {
	// Plugin must still implement the Plugin interface
	plugin.Plugin
	// Concrete implementation, written in Go. This is only used for plugins
	// that are written in Go.
	Impl shared.KVInterface
}

// GRPCClient - Required method to implement Plugin interface
func (p *Plugin) GRPCClient(ctx context.Context, broker *plugin.GRPCBroker, c *grpcx.ClientConn) (interface{}, error) {
	return &Client{client: base.NewKVClient(c)}, nil
}

// GRPCServer - Required method to implement Plugin interface
func (p *Plugin) GRPCServer(broker *plugin.GRPCBroker, s *grpcx.Server) error {
	base.RegisterKVServer(s, &Server{Impl: p.Impl})
	return nil
}
