// Code generated by protoc-gen-hcplugin. DO NOT EDIT.
package cmd

import (
	cli "github.com/urfave/cli"

	shared "github.com/da-moon/protoc-gen-hcplugin/example/proto/kv/shared"
)

// Client - this is the client that talks to engine
var Client shared.KVInterface

// GetImpl - this function is called in the implmentation of get cmd operation and should be set by the developer
var GetImpl func(ctx *cli.Context) error

// Get - cmd interface implmentation
func Get(ctx *cli.Context) error {
	return GetImpl(ctx)
}

// PutImpl - this function is called in the implmentation of put cmd operation and should be set by the developer
var PutImpl func(ctx *cli.Context) error

// Put - cmd interface implmentation
func Put(ctx *cli.Context) error {
	return PutImpl(ctx)
}
