// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto1 "github.com/da-moon/protoc-gen-hcplugin/internal/helper/utils/proto"
	_ "github.com/da-moon/protoc-gen-hcplugin/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Package struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	PackagePath          string   `protobuf:"bytes,2,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}
func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *Package) GetPackagePath() string {
	if m != nil {
		return m.PackagePath
	}
	return ""
}

type Input struct {
	FieldName            string   `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldValue           string   `protobuf:"bytes,2,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}
func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *Input) GetFieldValue() string {
	if m != nil {
		return m.FieldValue
	}
	return ""
}

type Base struct {
	Package              string             `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Imports              map[string]Package `protobuf:"bytes,2,rep,name=imports,proto3" json:"imports" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Services             []Service          `protobuf:"bytes,3,rep,name=services,proto3" json:"services"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Base) Reset()         { *m = Base{} }
func (m *Base) String() string { return proto.CompactTextString(m) }
func (*Base) ProtoMessage()    {}
func (*Base) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}
func (m *Base) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base.Unmarshal(m, b)
}
func (m *Base) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base.Marshal(b, m, deterministic)
}
func (m *Base) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base.Merge(m, src)
}
func (m *Base) XXX_Size() int {
	return xxx_messageInfo_Base.Size(m)
}
func (m *Base) XXX_DiscardUnknown() {
	xxx_messageInfo_Base.DiscardUnknown(m)
}

var xxx_messageInfo_Base proto.InternalMessageInfo

func (m *Base) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Base) GetImports() map[string]Package {
	if m != nil {
		return m.Imports
	}
	return nil
}

func (m *Base) GetServices() []Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	ServiceName          proto1.String `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name"`
	Methods              []Method      `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceName() proto1.String {
	if m != nil {
		return m.ServiceName
	}
	return proto1.String{}
}

func (m *Service) GetMethods() []Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

type Method struct {
	// MethodSignature method_signature = 1;
	// string request_getter = 3;
	// string response_getter = 4;
	// string request_setter = 5;
	// string response_setter = 6;
	InputType            string        `protobuf:"bytes,1,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	OutputType           string        `protobuf:"bytes,2,opt,name=output_type,json=outputType,proto3" json:"output_type,omitempty"`
	Name                 proto1.String `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	InputFields          []Field       `protobuf:"bytes,4,rep,name=input_fields,json=inputFields,proto3" json:"input_fields"`
	OutputFields         []Field       `protobuf:"bytes,5,rep,name=output_fields,json=outputFields,proto3" json:"output_fields"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}
func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetInputType() string {
	if m != nil {
		return m.InputType
	}
	return ""
}

func (m *Method) GetOutputType() string {
	if m != nil {
		return m.OutputType
	}
	return ""
}

func (m *Method) GetName() proto1.String {
	if m != nil {
		return m.Name
	}
	return proto1.String{}
}

func (m *Method) GetInputFields() []Field {
	if m != nil {
		return m.InputFields
	}
	return nil
}

func (m *Method) GetOutputFields() []Field {
	if m != nil {
		return m.OutputFields
	}
	return nil
}

type MethodSignature struct {
	Expanded             string   `protobuf:"bytes,1,opt,name=expanded,proto3" json:"expanded,omitempty"`
	ExpandedWithErr      string   `protobuf:"bytes,2,opt,name=expanded_with_err,json=expandedWithErr,proto3" json:"expanded_with_err,omitempty"`
	Proto                string   `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`
	ProtoWithErr         string   `protobuf:"bytes,4,opt,name=proto_with_err,json=protoWithErr,proto3" json:"proto_with_err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodSignature) Reset()         { *m = MethodSignature{} }
func (m *MethodSignature) String() string { return proto.CompactTextString(m) }
func (*MethodSignature) ProtoMessage()    {}
func (*MethodSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}
func (m *MethodSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodSignature.Unmarshal(m, b)
}
func (m *MethodSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodSignature.Marshal(b, m, deterministic)
}
func (m *MethodSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodSignature.Merge(m, src)
}
func (m *MethodSignature) XXX_Size() int {
	return xxx_messageInfo_MethodSignature.Size(m)
}
func (m *MethodSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodSignature.DiscardUnknown(m)
}

var xxx_messageInfo_MethodSignature proto.InternalMessageInfo

func (m *MethodSignature) GetExpanded() string {
	if m != nil {
		return m.Expanded
	}
	return ""
}

func (m *MethodSignature) GetExpandedWithErr() string {
	if m != nil {
		return m.ExpandedWithErr
	}
	return ""
}

func (m *MethodSignature) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *MethodSignature) GetProtoWithErr() string {
	if m != nil {
		return m.ProtoWithErr
	}
	return ""
}

type Field struct {
	// key -> prefix (* , & ) value -> Name
	VariableName proto1.KV `protobuf:"bytes,1,opt,name=variable_name,json=variableName,proto3" json:"variable_name"`
	// key -> package (* , & ) value -> Type
	VariableType proto1.KV `protobuf:"bytes,2,opt,name=variable_type,json=variableType,proto3" json:"variable_type"`
	// key -> import name (* , & ) value -> import path
	Package proto1.KV `protobuf:"bytes,3,opt,name=package,proto3" json:"package"`
	// gogo field options
	GoGoFieldOptions     *GoGoFieldOptions `protobuf:"bytes,4,opt,name=go_go_field_options,json=goGoFieldOptions,proto3" json:"go_go_field_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetVariableName() proto1.KV {
	if m != nil {
		return m.VariableName
	}
	return proto1.KV{}
}

func (m *Field) GetVariableType() proto1.KV {
	if m != nil {
		return m.VariableType
	}
	return proto1.KV{}
}

func (m *Field) GetPackage() proto1.KV {
	if m != nil {
		return m.Package
	}
	return proto1.KV{}
}

func (m *Field) GetGoGoFieldOptions() *GoGoFieldOptions {
	if m != nil {
		return m.GoGoFieldOptions
	}
	return nil
}

type GoGoFieldOptions struct {
	CustomName           string   `protobuf:"bytes,1,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	EnumCustomName       string   `protobuf:"bytes,2,opt,name=enum_custom_name,json=enumCustomName,proto3" json:"enum_custom_name,omitempty"`
	CustomType           string   `protobuf:"bytes,3,opt,name=custom_type,json=customType,proto3" json:"custom_type,omitempty"`
	STDTime              bool     `protobuf:"varint,4,opt,name=std_time,json=stdTime,proto3" json:"std_time,omitempty"`
	STDDuration          bool     `protobuf:"varint,5,opt,name=std_duration,json=stdDuration,proto3" json:"std_duration,omitempty"`
	Nullable             bool     `protobuf:"varint,6,opt,name=nullable,proto3" json:"nullable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoGoFieldOptions) Reset()         { *m = GoGoFieldOptions{} }
func (m *GoGoFieldOptions) String() string { return proto.CompactTextString(m) }
func (*GoGoFieldOptions) ProtoMessage()    {}
func (*GoGoFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}
func (m *GoGoFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoGoFieldOptions.Unmarshal(m, b)
}
func (m *GoGoFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoGoFieldOptions.Marshal(b, m, deterministic)
}
func (m *GoGoFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoGoFieldOptions.Merge(m, src)
}
func (m *GoGoFieldOptions) XXX_Size() int {
	return xxx_messageInfo_GoGoFieldOptions.Size(m)
}
func (m *GoGoFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GoGoFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GoGoFieldOptions proto.InternalMessageInfo

func (m *GoGoFieldOptions) GetCustomName() string {
	if m != nil {
		return m.CustomName
	}
	return ""
}

func (m *GoGoFieldOptions) GetEnumCustomName() string {
	if m != nil {
		return m.EnumCustomName
	}
	return ""
}

func (m *GoGoFieldOptions) GetCustomType() string {
	if m != nil {
		return m.CustomType
	}
	return ""
}

func (m *GoGoFieldOptions) GetSTDTime() bool {
	if m != nil {
		return m.STDTime
	}
	return false
}

func (m *GoGoFieldOptions) GetSTDDuration() bool {
	if m != nil {
		return m.STDDuration
	}
	return false
}

func (m *GoGoFieldOptions) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func init() {
	proto.RegisterType((*Package)(nil), "model.Package")
	proto.RegisterType((*Input)(nil), "model.Input")
	proto.RegisterType((*Base)(nil), "model.Base")
	proto.RegisterMapType((map[string]Package)(nil), "model.Base.ImportsEntry")
	proto.RegisterType((*Service)(nil), "model.Service")
	proto.RegisterType((*Method)(nil), "model.Method")
	proto.RegisterType((*MethodSignature)(nil), "model.MethodSignature")
	proto.RegisterType((*Field)(nil), "model.Field")
	proto.RegisterType((*GoGoFieldOptions)(nil), "model.GoGoFieldOptions")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xf3, 0x44,
	0x10, 0x8e, 0x9b, 0xa4, 0x4e, 0xc7, 0x6e, 0x1b, 0x16, 0x24, 0xac, 0x48, 0x34, 0xef, 0x6b, 0x2a,
	0x54, 0x21, 0x25, 0xa9, 0x82, 0x10, 0x15, 0x12, 0x97, 0xd0, 0x0f, 0x15, 0x04, 0xad, 0x9c, 0xa8,
	0x1c, 0x2d, 0x27, 0xde, 0xda, 0x4b, 0x6d, 0xaf, 0x65, 0xaf, 0x0b, 0xf9, 0x21, 0xfc, 0xa7, 0x1e,
	0x39, 0x70, 0x40, 0x42, 0xaa, 0x50, 0x7e, 0x04, 0x67, 0xb4, 0xb3, 0xeb, 0x24, 0xad, 0xca, 0x81,
	0xdb, 0xcc, 0x33, 0xcf, 0x7c, 0x3e, 0xbb, 0x60, 0xa5, 0x3c, 0xa4, 0xc9, 0x30, 0x2f, 0xb8, 0xe0,
	0xa4, 0x8d, 0x4e, 0xef, 0x9b, 0x88, 0x89, 0xb8, 0x9a, 0x0f, 0x17, 0x3c, 0x1d, 0xcd, 0xd9, 0x7d,
	0xc1, 0x4b, 0xb1, 0x48, 0x78, 0x15, 0x8e, 0x90, 0xb5, 0x18, 0x44, 0x34, 0x1b, 0xc4, 0x8b, 0x3c,
	0xa9, 0x22, 0x96, 0x29, 0x6c, 0x24, 0x96, 0x39, 0x2d, 0x55, 0x95, 0xde, 0xf4, 0xff, 0xa4, 0xb3,
	0x4c, 0xd0, 0x22, 0x0b, 0x92, 0x51, 0x4c, 0x93, 0x9c, 0x16, 0xa3, 0x4a, 0xb0, 0xa4, 0xd4, 0x45,
	0xd1, 0xd6, 0x45, 0x07, 0x5b, 0x45, 0x23, 0x1e, 0x71, 0x45, 0x99, 0x57, 0xf7, 0xe8, 0x29, 0xbe,
	0xb4, 0x14, 0xdd, 0xbd, 0x01, 0xf3, 0x36, 0x58, 0x3c, 0x04, 0x11, 0x25, 0xef, 0xc1, 0xce, 0x95,
	0xe9, 0x67, 0x41, 0x4a, 0x1d, 0xe3, 0x9d, 0x71, 0xb2, 0xe7, 0x59, 0x1a, 0xfb, 0x31, 0x48, 0x5f,
	0x50, 0xf2, 0x40, 0xc4, 0xce, 0xce, 0x0b, 0xca, 0x6d, 0x20, 0x62, 0xf7, 0x0a, 0xda, 0xd7, 0x59,
	0x5e, 0x09, 0xf2, 0x09, 0xc0, 0x3d, 0xa3, 0x49, 0xb8, 0x5d, 0x6c, 0x0f, 0x11, 0x2c, 0xd5, 0x07,
	0x4b, 0x85, 0x1f, 0x83, 0xa4, 0xa2, 0xba, 0x92, 0xca, 0xb8, 0x93, 0x88, 0xfb, 0xa7, 0x01, 0xad,
	0x49, 0x50, 0x52, 0xe2, 0x80, 0xa9, 0x1b, 0xe8, 0x2a, 0xb5, 0x4b, 0xce, 0xc0, 0x64, 0x69, 0xce,
	0x0b, 0x51, 0x3a, 0x3b, 0xef, 0x9a, 0x27, 0xd6, 0xd8, 0x19, 0x2a, 0x95, 0x64, 0xde, 0xf0, 0x5a,
	0x85, 0x2e, 0x32, 0x51, 0x2c, 0x27, 0xad, 0xa7, 0xe7, 0x7e, 0xc3, 0xab, 0xe9, 0xe4, 0x14, 0x3a,
	0x25, 0x2d, 0x1e, 0xd9, 0x82, 0x96, 0x4e, 0x13, 0x53, 0x0f, 0x74, 0xea, 0x54, 0xc1, 0x3a, 0x61,
	0xcd, 0xea, 0x7d, 0x07, 0xf6, 0x76, 0x41, 0xd2, 0x85, 0xe6, 0x03, 0x5d, 0xea, 0x89, 0xa4, 0x49,
	0x8e, 0xa1, 0xbd, 0xd9, 0x65, 0x53, 0x50, 0x9f, 0xd7, 0x53, 0xc1, 0xaf, 0x77, 0xce, 0x0c, 0xf7,
	0x67, 0x30, 0x75, 0x1b, 0x72, 0x0a, 0xb6, 0x6e, 0xb1, 0xb9, 0x93, 0x35, 0x36, 0x87, 0x53, 0x51,
	0xb0, 0x2c, 0xd2, 0x53, 0x58, 0x9a, 0x82, 0x87, 0x1b, 0x80, 0x99, 0x52, 0x11, 0xf3, 0xb0, 0x5e,
	0x7a, 0x5f, 0x37, 0xfa, 0x01, 0xd1, 0x7a, 0x53, 0xcd, 0x71, 0xff, 0x32, 0x60, 0x57, 0x45, 0xa4,
	0x22, 0x4c, 0x4a, 0xe3, 0xcb, 0x47, 0x58, 0x2b, 0x82, 0xc8, 0x6c, 0x99, 0xa3, 0x22, 0xbc, 0x12,
	0xeb, 0xb8, 0x56, 0x44, 0x41, 0x48, 0x78, 0x0f, 0x2d, 0x9c, 0xb1, 0xf9, 0xd6, 0x8c, 0x18, 0x22,
	0x5f, 0x82, 0xad, 0x5a, 0xa0, 0x90, 0xa5, 0xd3, 0xc2, 0x09, 0x6d, 0x3d, 0xe1, 0xa5, 0x04, 0xeb,
	0x9d, 0x90, 0x87, 0x48, 0x49, 0xbe, 0x82, 0x7d, 0xdd, 0x5a, 0xe7, 0xb5, 0xff, 0x33, 0xcf, 0x56,
	0x44, 0x95, 0xe8, 0xfe, 0x66, 0xc0, 0xa1, 0xda, 0x6e, 0xca, 0xa2, 0x2c, 0x10, 0x55, 0x41, 0x49,
	0x0f, 0x3a, 0xf4, 0xd7, 0x3c, 0xc8, 0x42, 0x1a, 0xea, 0x25, 0xd7, 0x3e, 0xf9, 0x1c, 0x3e, 0xa8,
	0x6d, 0xff, 0x17, 0x26, 0x62, 0x9f, 0x16, 0x85, 0xde, 0xf4, 0xb0, 0x0e, 0xfc, 0xc4, 0x44, 0x7c,
	0x51, 0x14, 0xe4, 0x23, 0x68, 0xe3, 0x1f, 0xc1, 0x7d, 0xf7, 0x3c, 0xe5, 0x90, 0x63, 0x38, 0x40,
	0x63, 0x93, 0xde, 0xc2, 0xb0, 0x8d, 0xa8, 0xce, 0x75, 0xff, 0x30, 0xa0, 0x8d, 0x23, 0x92, 0x21,
	0xec, 0x3f, 0x06, 0x05, 0x0b, 0xe6, 0xc9, 0x0b, 0x85, 0x9b, 0xc3, 0xef, 0xef, 0xea, 0x8d, 0xea,
	0x38, 0xca, 0xbb, 0xcd, 0x5f, 0xeb, 0xf0, 0x36, 0x1f, 0x45, 0xf9, 0x74, 0xf3, 0x3b, 0x9a, 0xaf,
	0x99, 0xeb, 0x8f, 0x72, 0x09, 0x1f, 0x46, 0xdc, 0x8f, 0xb8, 0x3a, 0xaf, 0xcf, 0x73, 0xc1, 0x78,
	0x56, 0xe2, 0xe4, 0xd6, 0xf8, 0x63, 0x7d, 0xe5, 0x2b, 0x7e, 0xc5, 0x71, 0xe6, 0x1b, 0x15, 0xf6,
	0xba, 0xd1, 0x2b, 0xc4, 0xfd, 0xc7, 0x80, 0xee, 0x6b, 0x9a, 0x7c, 0x37, 0x8b, 0xaa, 0x14, 0x3c,
	0xdd, 0xfe, 0xe9, 0xa0, 0x20, 0x5c, 0xe9, 0x04, 0xba, 0x34, 0xab, 0x52, 0x7f, 0x9b, 0xa5, 0x6e,
	0x7e, 0x20, 0xf1, 0x6f, 0x37, 0xcc, 0x4d, 0x29, 0x5c, 0xbd, 0xb9, 0x5d, 0x0a, 0xb7, 0xfd, 0x0c,
	0x3a, 0xa5, 0x08, 0x7d, 0xc1, 0x52, 0x8a, 0xd3, 0x77, 0x26, 0xd6, 0xea, 0xb9, 0x6f, 0x4e, 0x67,
	0xe7, 0x33, 0x96, 0x52, 0xcf, 0x2c, 0x45, 0x28, 0x0d, 0x32, 0x06, 0x5b, 0xf2, 0xc2, 0xaa, 0x08,
	0xe4, 0x90, 0x4e, 0x1b, 0xb9, 0x87, 0xab, 0xe7, 0xbe, 0x35, 0x9d, 0x9d, 0x9f, 0x6b, 0xd8, 0xb3,
	0x4a, 0x11, 0xd6, 0x8e, 0x7c, 0x37, 0x59, 0x95, 0x24, 0xf2, 0xb2, 0xce, 0xae, 0xe4, 0x7b, 0x6b,
	0x7f, 0x62, 0x3f, 0xad, 0x8e, 0x1a, 0xbf, 0xaf, 0x8e, 0x1a, 0x7f, 0xaf, 0x8e, 0x1a, 0xf3, 0x5d,
	0xd4, 0xfa, 0x8b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x70, 0xbf, 0xd2, 0x95, 0x14, 0x06, 0x00,
	0x00,
}
