// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: utils.proto

package utils

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type String struct {
	Original             string   `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	LowerCamelCase       string   `protobuf:"bytes,2,opt,name=lower_camel_case,json=lowerCamelCase,proto3" json:"lower_camel_case,omitempty"`
	UpperCamelCase       string   `protobuf:"bytes,3,opt,name=upper_camel_case,json=upperCamelCase,proto3" json:"upper_camel_case,omitempty"`
	LowerSnakeCase       string   `protobuf:"bytes,4,opt,name=lower_snake_case,json=lowerSnakeCase,proto3" json:"lower_snake_case,omitempty"`
	UpperSnakeCase       string   `protobuf:"bytes,5,opt,name=upper_snake_case,json=upperSnakeCase,proto3" json:"upper_snake_case,omitempty"`
	LowerDotCase         string   `protobuf:"bytes,6,opt,name=lower_dot_case,json=lowerDotCase,proto3" json:"lower_dot_case,omitempty"`
	UpperDotCase         string   `protobuf:"bytes,7,opt,name=upper_dot_case,json=upperDotCase,proto3" json:"upper_dot_case,omitempty"`
	LowerParamCase       string   `protobuf:"bytes,8,opt,name=lower_param_case,json=lowerParamCase,proto3" json:"lower_param_case,omitempty"`
	UpperParamCase       string   `protobuf:"bytes,9,opt,name=upper_param_case,json=upperParamCase,proto3" json:"upper_param_case,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{0}
}
func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

func (m *String) GetLowerCamelCase() string {
	if m != nil {
		return m.LowerCamelCase
	}
	return ""
}

func (m *String) GetUpperCamelCase() string {
	if m != nil {
		return m.UpperCamelCase
	}
	return ""
}

func (m *String) GetLowerSnakeCase() string {
	if m != nil {
		return m.LowerSnakeCase
	}
	return ""
}

func (m *String) GetUpperSnakeCase() string {
	if m != nil {
		return m.UpperSnakeCase
	}
	return ""
}

func (m *String) GetLowerDotCase() string {
	if m != nil {
		return m.LowerDotCase
	}
	return ""
}

func (m *String) GetUpperDotCase() string {
	if m != nil {
		return m.UpperDotCase
	}
	return ""
}

func (m *String) GetLowerParamCase() string {
	if m != nil {
		return m.LowerParamCase
	}
	return ""
}

func (m *String) GetUpperParamCase() string {
	if m != nil {
		return m.UpperParamCase
	}
	return ""
}

type KV struct {
	Key                  String   `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value                String   `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91c651f4717a5f2, []int{1}
}
func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() String {
	if m != nil {
		return m.Key
	}
	return String{}
}

func (m *KV) GetValue() String {
	if m != nil {
		return m.Value
	}
	return String{}
}

func init() {
	proto.RegisterType((*String)(nil), "String")
	proto.RegisterType((*KV)(nil), "KV")
}

func init() { proto.RegisterFile("utils.proto", fileDescriptor_c91c651f4717a5f2) }

var fileDescriptor_c91c651f4717a5f2 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd2, 0xc1, 0x4e, 0xab, 0x40,
	0x14, 0x06, 0x60, 0x4a, 0x0b, 0x6d, 0xa7, 0x37, 0x37, 0x06, 0x37, 0x4d, 0x17, 0xd4, 0x54, 0x17,
	0xdd, 0x48, 0x13, 0x7d, 0x83, 0xd6, 0x95, 0x6e, 0x4c, 0x9b, 0xb8, 0x70, 0x43, 0x06, 0x1c, 0x91,
	0x74, 0x60, 0xc8, 0x30, 0xa3, 0xf1, 0x0d, 0xbb, 0xf4, 0x09, 0x8c, 0x61, 0xed, 0x43, 0x98, 0x39,
	0x27, 0xc5, 0x21, 0xee, 0x98, 0x7f, 0x3e, 0xfe, 0x9c, 0x1c, 0x20, 0x13, 0xad, 0x72, 0x5e, 0x47,
	0x95, 0x14, 0x4a, 0xcc, 0x2e, 0xb3, 0x5c, 0xbd, 0xe8, 0x24, 0x4a, 0x45, 0xb1, 0xca, 0x44, 0x26,
	0x56, 0x10, 0x27, 0xfa, 0x19, 0x4e, 0x70, 0x80, 0x27, 0xe4, 0x8b, 0x6f, 0x97, 0xf8, 0x3b, 0x25,
	0xf3, 0x32, 0x0b, 0x66, 0x64, 0x24, 0x64, 0x9e, 0xe5, 0x25, 0xe5, 0xd3, 0xde, 0x59, 0x6f, 0x39,
	0xde, 0xb6, 0xe7, 0x60, 0x49, 0x4e, 0xb8, 0x78, 0x63, 0x32, 0x4e, 0x69, 0xc1, 0x78, 0x9c, 0xd2,
	0x9a, 0x4d, 0x5d, 0x30, 0xff, 0x21, 0xdf, 0x98, 0x78, 0x43, 0x6b, 0x66, 0xa4, 0xae, 0xaa, 0xae,
	0xec, 0xa3, 0x84, 0xbc, 0x23, 0xb1, 0xb3, 0x2e, 0xe9, 0x9e, 0xa1, 0x1c, 0x58, 0x9d, 0x3b, 0x13,
	0x77, 0x3b, 0x2d, 0xe9, 0x59, 0x9d, 0xbf, 0xf2, 0x82, 0xe0, 0xbb, 0xf1, 0x93, 0x50, 0xe8, 0x7c,
	0x70, 0xff, 0x20, 0xbd, 0x11, 0xea, 0xa8, 0xb0, 0xaf, 0x55, 0x43, 0x54, 0x90, 0x1e, 0x55, 0x3b,
	0x5f, 0x45, 0x25, 0x2d, 0xd0, 0x8d, 0xac, 0xf9, 0xee, 0x4d, 0xdc, 0x9d, 0xcf, 0x92, 0x63, 0x6b,
	0xbe, 0x56, 0x2e, 0x6e, 0x89, 0x7b, 0xf7, 0x10, 0xcc, 0x49, 0x7f, 0xcf, 0xde, 0x61, 0xc9, 0x93,
	0xab, 0x61, 0x84, 0xfb, 0x5f, 0x0f, 0x0e, 0x9f, 0x73, 0x67, 0x6b, 0x6e, 0x82, 0x73, 0xe2, 0xbd,
	0x52, 0xae, 0x71, 0xc7, 0x7f, 0x08, 0xde, 0xad, 0x4f, 0x0f, 0x4d, 0xe8, 0x7c, 0x34, 0xa1, 0xf3,
	0xd5, 0x84, 0xce, 0xa3, 0x07, 0x3f, 0x41, 0xe2, 0xc3, 0x67, 0xbd, 0xfe, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x19, 0x31, 0xd9, 0x1f, 0x14, 0x02, 0x00, 0x00,
}
