// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Handshake struct {
	ProtocolVersion      uint32   `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MagicCookieKey       string   `protobuf:"bytes,2,opt,name=magic_cookie_key,json=magicCookieKey,proto3" json:"magic_cookie_key,omitempty"`
	MagicCookieValue     string   `protobuf:"bytes,3,opt,name=magic_cookie_value,json=magicCookieValue,proto3" json:"magic_cookie_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}
func (*Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handshake.Unmarshal(m, b)
}
func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handshake.Marshal(b, m, deterministic)
}
func (m *Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handshake.Merge(m, src)
}
func (m *Handshake) XXX_Size() int {
	return xxx_messageInfo_Handshake.Size(m)
}
func (m *Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_Handshake proto.InternalMessageInfo

func (m *Handshake) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *Handshake) GetMagicCookieKey() string {
	if m != nil {
		return m.MagicCookieKey
	}
	return ""
}

func (m *Handshake) GetMagicCookieValue() string {
	if m != nil {
		return m.MagicCookieValue
	}
	return ""
}

type CMD struct {
	// override service name
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Usage                string   `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Aliases              []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMD) Reset()         { *m = CMD{} }
func (m *CMD) String() string { return proto.CompactTextString(m) }
func (*CMD) ProtoMessage()    {}
func (*CMD) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *CMD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMD.Unmarshal(m, b)
}
func (m *CMD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMD.Marshal(b, m, deterministic)
}
func (m *CMD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMD.Merge(m, src)
}
func (m *CMD) XXX_Size() int {
	return xxx_messageInfo_CMD.Size(m)
}
func (m *CMD) XXX_DiscardUnknown() {
	xxx_messageInfo_CMD.DiscardUnknown(m)
}

var xxx_messageInfo_CMD proto.InternalMessageInfo

func (m *CMD) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CMD) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *CMD) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

var E_CmdServiceOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*CMD)(nil),
	Field:         999996,
	Name:          "cmd_service_options",
	Tag:           "bytes,999996,opt,name=cmd_service_options",
	Filename:      "types.proto",
}

var E_Handshake = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*Handshake)(nil),
	Field:         999998,
	Name:          "handshake",
	Tag:           "bytes,999998,opt,name=handshake",
	Filename:      "types.proto",
}

var E_CmdMethodOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*CMD)(nil),
	Field:         999999,
	Name:          "cmd_method_options",
	Tag:           "bytes,999999,opt,name=cmd_method_options",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*Handshake)(nil), "Handshake")
	proto.RegisterType((*CMD)(nil), "CMD")
	proto.RegisterExtension(E_CmdServiceOptions)
	proto.RegisterExtension(E_Handshake)
	proto.RegisterExtension(E_CmdMethodOptions)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x53, 0x95, 0x4c, 0x51, 0xe3, 0xea, 0x21, 0x78, 0xd0, 0xd0, 0x53, 0x04, 0x49,
	0x41, 0x6f, 0x05, 0x2f, 0xb6, 0x07, 0xa5, 0x14, 0x21, 0x4a, 0x05, 0x2f, 0x61, 0xbb, 0x19, 0xd3,
	0xa5, 0x49, 0x26, 0x64, 0xd3, 0x42, 0xef, 0x9e, 0xfd, 0x45, 0xa2, 0x7f, 0x4d, 0xba, 0x69, 0xaa,
	0xc1, 0x83, 0xb7, 0x9d, 0xb7, 0xdf, 0xbc, 0x79, 0x3c, 0xe8, 0x94, 0xab, 0x1c, 0x95, 0x9f, 0x17,
	0x54, 0xd2, 0xa9, 0x1b, 0x13, 0xc5, 0x09, 0xf6, 0xf4, 0x34, 0x5d, 0xbc, 0xf6, 0x22, 0x54, 0xa2,
	0x90, 0x79, 0x49, 0x45, 0x45, 0x74, 0xdf, 0x0d, 0xb0, 0xee, 0x78, 0x16, 0xa9, 0x19, 0x9f, 0x23,
	0xbb, 0x00, 0x5b, 0xcb, 0x82, 0x92, 0x70, 0x89, 0x85, 0x92, 0x94, 0x39, 0x86, 0x6b, 0x78, 0xfb,
	0xc1, 0x61, 0xad, 0x4f, 0x2a, 0x99, 0x79, 0x60, 0xa7, 0x3c, 0x96, 0x22, 0x14, 0x44, 0x73, 0x89,
	0xe1, 0x1c, 0x57, 0x4e, 0xcb, 0x35, 0x3c, 0x2b, 0x38, 0xd0, 0xfa, 0x40, 0xcb, 0x23, 0x5c, 0xb1,
	0x4b, 0x60, 0x0d, 0x72, 0xc9, 0x93, 0x05, 0x3a, 0xa6, 0x66, 0xed, 0x5f, 0xec, 0x64, 0xad, 0x77,
	0xef, 0xc1, 0x1c, 0x8c, 0x87, 0x8c, 0x41, 0x3b, 0xe3, 0x29, 0xea, 0xeb, 0x56, 0xa0, 0xdf, 0xec,
	0x04, 0x76, 0x16, 0x8a, 0xc7, 0xb8, 0xb9, 0x53, 0x0d, 0xcc, 0x81, 0x3d, 0x9e, 0x48, 0xae, 0x50,
	0x39, 0xa6, 0x6b, 0x7a, 0x56, 0x50, 0x8f, 0xfd, 0x67, 0x38, 0x16, 0x69, 0x14, 0x2a, 0x2c, 0x96,
	0x52, 0x60, 0x48, 0x79, 0x29, 0x29, 0x53, 0xec, 0xdc, 0xaf, 0x5a, 0xf1, 0xeb, 0x56, 0xfc, 0xc7,
	0x8a, 0x78, 0xa8, 0x00, 0xe7, 0xe3, 0xed, 0xc6, 0x35, 0xbc, 0xce, 0x55, 0xdb, 0x1f, 0x8c, 0x87,
	0xc1, 0x91, 0x48, 0xa3, 0x26, 0xd0, 0x1f, 0x81, 0x35, 0xdb, 0x76, 0xf6, 0xaf, 0xdd, 0xe7, 0xc6,
	0x0e, 0xfc, 0x6d, 0xd1, 0xc1, 0xcf, 0x7e, 0xff, 0x09, 0xd8, 0x3a, 0x65, 0x8a, 0xe5, 0x8c, 0xa2,
	0x6d, 0xc8, 0xb3, 0x3f, 0xae, 0x63, 0x0d, 0xd4, 0xa6, 0x5f, 0x8d, 0x8c, 0xb6, 0x48, 0xa3, 0xc6,
	0xff, 0x6d, 0xfb, 0xa5, 0x95, 0x4f, 0xa7, 0xbb, 0x7a, 0xfb, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x42, 0x9b, 0x82, 0x57, 0x15, 0x02, 0x00, 0x00,
}
