// Code generated by protoc-gen-hcplugin. DO NOT EDIT.
package engine

import (
	grpc "github.com/da-moon/protoc-gen-hcplugin/example/proto/kv/grpc"

	plugin "github.com/hashicorp/go-plugin"

	shared "github.com/da-moon/protoc-gen-hcplugin/example/proto/kv/shared"
)

// ServeConfig - This is the plugin config thet is used in main function of engine
func ServeConfig() *plugin.ServeConfig {
	return &plugin.ServeConfig{
		HandshakeConfig: shared.HandshakeConfig,
		Plugins: map[string]plugin.Plugin{
			"kv": &grpc.Plugin{Impl: &KV{}},
		},
		// A non-nil value here enables gRPC serving for this plugin...
		GRPCServer: plugin.DefaultGRPCServer,
	}
}

// KV - this is the struct that implements engine operations
type KV struct{}

// GetImpl - this function is called in the implmentation of get operation and should be set by the developer
var GetImpl func(key string) ([]byte, error)

// Get - Implementation of Get method for go engine
func (KV) Get(key string) ([]byte, error) {
	return GetImpl(key)
}

// PutImpl - this function is called in the implmentation of put operation and should be set by the developer
var PutImpl func(key string, value []byte) error

// Put - Implementation of Put method for go engine
func (KV) Put(key string, value []byte) error {
	return PutImpl(key, value)
}
